services:
  mssqldb:
    build:
      context: db
      dockerfile: mssql.Dockerfile
    environment:
      # some clients set the default password on different env vars
      SA_PASSWORD: "Your_password123"
      MSSQL_SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      TZ: "UTC"
      # if you want to load the BAK, set this to true. 
      # note that this will OVERWRITE your current data, you probably just want to use migrate to 
      #   update your DB unless you're just getting started.
      LOAD_DB_BAK: "${LOAD_DB_BAK:-false}"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD}" -Q
        "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - asrm_network
    ports:
      - "1433:1433"
    volumes:
      - database-data-mssql:/var/opt/mssql
    container_name: mssql-db


volumes:
  database-data-mssql:

networks:
  asrm_network:
    driver: bridge
